version: '3.7'
services:
  api:
    image: api-service
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .docker.env
    ports:
      - '8080:8080'
    depends_on:
      - db
    volumes:
      - api_persist:/app
    networks:
      - network
  db:
    image: postgres:16.2-alpine
    restart: always
    env_file:
      - .docker.env
    ports:
      - '5432:5432'
    volumes:
      - data_persist:/var/lib/postgresql/data
    networks:
      - network
volumes:
  api_persist:
    driver: local
  data_persist:
    driver: local
networks:
  network:
    driver: bridge
