// Nest Packages

// Custom Packages
import { ExceptionPayload } from '../types/exception.payload';

/**
 * RootException
 *
 * All of the custom exceptions will be generated by extending this Abstract Class through createException
 *
 */
export abstract class RootException<
  T extends ExceptionPayload = ExceptionPayload,
  U extends number = number,
> {
  // Set every message to readonly
  constructor(
    public readonly message: T,
    public readonly statuscode: U,
  ) {}
}
