// Nest Packages

// Custom Packages
import { ExceptionPayload } from '../types/exception.payload';

/**
 * RootException
 *
 * All of the custom exceptions will be generated by extending this Abstract Class through createException
 *
 */
export abstract class RootException<
  T extends ExceptionPayload = ExceptionPayload,
  U extends number = number,
> extends Error {
  public stack?: string;
  public message: string;

  // Set every message to readonly
  constructor(
    public readonly payload: T,
    public readonly statuscode: U,
    public readonly name: string,
  ) {
    super();
    // In case of custom exception class, it'll only allow  string error message
    this.message = payload.message as string;
  }
}
